### ISSUE TITLE
Idea identity

### ISSUE THREAD

**Issue by crisptrutski** [votepourca/geoforms#12]
Currently using Firebase generated IDs, but there is no validation that titles are unique.

Using distributed IDs is nice, we get ordering and non-clobbering for free, but perhaps there should be validation on uniqueness.

**Comment by votepourca** [comment]
Ok...

**Comment by crisptrutski** [comment]
Think that adding validation that idea title is unique (locally) fine. If a title does get repeated, can recover via admin tools or rolling up on the client.

**Comment by votepourca** [comment]
An idea title can be the same, but not if the same district is attached to it. One unique idea per district is ok, but, I want to make sure an idea like "open a child restaurant" could be added in brooklyn and another in Queens... Each of these ideas would have different supporters, because these ideas could be developed in a different districts.
Should we rely on IDs then???

**Comment by crisptrutski** [comment]
Thanks for clarifying, I've updated #14 and will the refinement there. Yes we're relying on IDs (the uniqueness is a custom check, which can also be added to Firebase remote validation)
